spring:
  application:
    name: delivery-service
  config:
    import: configserver:http://localhost:19092   # Config Server 주소

server:
  port: 19096
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

logging:
  level:
    feign: DEBUG
    feign.Logger: DEBUG
    com.sparta.logistics.delivery.infrastructure.client: DEBUG
    com.sparta.logistics.delivery: DEBUG
    org.springframework.web: DEBUG