server:
  port: 19099

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/sparta_notification
    username: sparta_notification
    password: sparta_notification
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true