spring:
  application:
    name: company-service
  config:
    import: configserver:http://localhost:19092

server:
  port: 19097
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/