spring:
  application:
    name: product-service
  config:
    import: configserver:http://localhost:19092 # Config Server 주소
  datasource:
    url: jdbc:postgresql://localhost:15432/sparta_product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
server:
  port: 19098


eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
---
# todo : 추후 config 서버 가동 시 삭제하기
spring:
  cloud:
    config:
      enabled: false
