spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:15432/sparta_order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 19095
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

# todo : 추후 변경하기
product-service:
  url: http://localhost:19098/product-service

delivery-service:
  url: http://localhost:19098/delivery-service
service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
