spring:
  application:
    name: order-service
  config:
    import: configserver:http://localhost:19092 # Config Server 주소
  datasource:
    url: jdbc:postgresql://localhost:15432/sparta_order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 19095
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

springdoc:
  api-docs:
    path: /order-service/v3/api-docs
  swagger-ui:
    path: /order-service/swagger-ui.html

openapi:
  service:
    url: http://localhost:19091 # API Gateway 포트