server:
  port: 19094

spring:
  application:
    name: hub-service
  config:
    import: configserver:http://localhost:19092 # Config Server 주소
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 500
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/ # Eureka Server 주소

springdoc:
  api-docs:
    path: /hub-service/v3/api-docs
  swagger-ui:
    path: /hub-service/swagger-ui.html

openapi:
  service:
    url: http://localhost:19091 # API Gateway 포트