spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:15432/sparta_auth
    username: sparta_auth
    password: sparta_auth
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 19093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/